### ISSUE TITLE
handle markdown files

### ISSUE THREAD

**Issue by drahnr** [drahnr/cargo-spellcheck#37]
## Summary

Enable handling of `*.md` files, the infrastructure is already there and the handling that is necessary is mostly in `traverse.rs` and in `documentation.rs`

**Comment by zhiburt** [comment]
Hey @drahnr, I investigated this issue a bit and as I see there are a bunch of *todo*s in the code in regard of this issues. Which is really helpful.

Here's one comment which I'd love to have a cast light on :)

https://github.com/drahnr/cargo-spellcheck/blob/a26aee13113292f132774687ce1932807dc797b6/src/documentation.rs#L19-L23

It's no clear to me if you want reuse`Vec<TrimmedLiteral>` and create just a marker of a type of documentation it holds. 

Mainly as I see to use the current structure the work should be piled on existent types such as `TrimmedLiteral`.  But `TrimmedLiteral` cann't be build from markdown filles (`syn::parse_str` fails parsing it).

Firstly I tried to extract `TrimmedLiteral` with removed corresponding field and create additional type `RustTrimmedLiteral` which has this field . The idea was that markdown files produces `TrimmedLiteral` but rust files `RustTrimmedLiteral`. Eventually I hope there's another way here as this is far too complicated I would expect here, and that's why I am here :) 

And as I understand for getting literals out of markdown there must be used a `PlainOverlay` type, and specifically `mapping` field right?

____

Some thoughts out of my mind as I kinda stuck with that :disappointed:

**Comment by drahnr** [comment]
I'll write smth up in a few minutes - I have an idea how to solve this cleanly and also help making #18  testable as a sideeffect :)

**Comment by drahnr** [comment]
Please see #55 which includes most of what is needed :)

**Comment by drahnr** [comment]
@zhiburt #55 is almost done, given that, the fundamental structure is there :)

**Comment by drahnr** [comment]
So #55 is complete and merged, feel free to take a stab or assign the issue back to me and I'll take over :)

**Comment by zhiburt** [comment]
:smile: I actually take a shot ones to implement it but didn't got too far :disappointed: 
Sorry for my *delays*.

I'll try to put it in action one more and tell how it will be.

**Comment by zhiburt** [comment]
Got into frustration one more time :smile:
I see that probably only missed part is https://github.com/drahnr/cargo-spellcheck/blob/06940a5b78c354dcc9d71c52b73ad07ffb6ac77b/src/traverse/mod.rs#L357

Adding an item to the map allows to see the `.md` files in the output but awkwardly.

So I can't figure out how to put it on the rails properly yet :(
I you could give any clue would be helpful.

**Comment by drahnr** [comment]
That would be roughly my approach too to just use a range / span covering the full markdown file.

Did you fork the repo again? Lots changed and the `proc_macro2::Span` should not be used outside of `CheckableChunk` construction anymore.

Could you create a PR and add some comments on what particular thing / section you do not understand plus your current attempted changes, that would allow me to give you better directions :)

**Comment by zhiburt** [comment]
It's not working properly in any way :disappointed:.

You might take a look here.

https://github.com/drahnr/cargo-spellcheck/commit/e45125da9aaad9b31930272af7c5b82d237a1287

**Comment by drahnr** [comment]
You got pretty close, I wasn't sure so I implemented the surface part (almost the same as you did, take a look at https://github.com/drahnr/cargo-spellcheck/pull/74/commits/e535f383ae6d81ea8c9d180a3a2457353aa21497 ) which is soon going to hit master soon - but I this was just the first step and there were plenty of other issues with that and actually required #25 to almost implemented - which was a bit of a heavy weight

Don't get discouraged, I'll try to add some conceptual overview graphics so it's easier to understand the individual components better :)
